config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :products do
    collection {post :search, to: 'products#index' }
  end
  resources :manufacturers
  resources :categories
  resources :users
  resources :sessions, only: [:create]
  resources :activity_logs, only: [:index]
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'create_first_user' => 'users#create_first_user'
  root :to => 'products#index'

  post '/api/cu_manufacturer', to: 'sync_catalogs#manufacturer_update'
  post '/api/cu_category', to: 'sync_catalogs#category_update'
  post '/api/cu_product', to: 'sync_catalogs#product_update'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PartnerPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="container-fluid">
  <div class="row">
    <nav role="navigation" class="navbar">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav nav-pills">



          <% if current_user %>
              <div class="navbar-text"><span class="glyphicon glyphicon-user"></span> <%= current_user.username %>
              <% if is_admin %>
                  (администратор)
              </div>
                    <li> <%= link_to "Логирование", activity_logs_path  %></li>
                    <li> <%= link_to "Пользователи", users_path  %></li>
                    <li> <%= link_to "Товары", products_path %></li>
                    <% else %>
                    </div>
          <% end %>

              <li> <%= link_to "Выход", logout_url %></li>


        <% else %>

          <% end %>




        </ul>

        <ul class="nav navbar-nav navbar-right">

        </ul>
      </div>
    </nav>
  </div>
</div>

<%= yield %>

</body>
</html>